### ISSUE TITLE
error on video.js

### ISSUE THREAD

**Issue by mohsinalimat** [0x5eba/Video-Meeting#12]
Hello,

When run on my another system then below error comes.

![photo_2020-08-05 17 15 45](https://user-images.githubusercontent.com/973676/89409255-65db3e00-d73f-11ea-8d12-92a21021e5a4.jpeg)

**Comment by 0x5eba** [comment]
Try read this issue https://github.com/ant-media/Ant-Media-Server/issues/1200
Also remember to allow your camera and microphone. It doesn't work use firefox
