### ISSUE TITLE
How to install "yarn install" / "yarn dev"

### ISSUE THREAD

**Issue by emailbsuv** [0x5eba/Video-Meeting#17]
root@ubuntu:/var/www/html/meet# yarn dev
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'dev'
root@ubuntu:/var/www/html/meet# yarn install
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'

**Comment by 0x5eba** [comment]
https://classic.yarnpkg.com/en/docs/install/#debian-stable
