### ISSUE TITLE
TypeError: connections[socketListId].addStream is not a function

### ISSUE THREAD

**Issue by manjujidagi** [0x5eba/Video-Meeting#2]
Unable to join in Linux & Mac.

But The Below Error Screen is showing in MAC but not on Linux

 In 'connections[socketListId].addStream(window.localStream)', 'connections[socketListId].addStream' is undefined

![Screenshot 2020-05-28 at 12 56 30 PM](https://user-images.githubusercontent.com/17455675/83111732-aa64b080-a0e2-11ea-90e1-d02e8db7379d.png)

**Comment by 0x5eba** [comment]
The API only works on Chrome and Firefox.
Maybe when I will have more free time I will try with Safari and other browser too.
