### ISSUE TITLE
How to set the limit to number of particpants??

### ISSUE THREAD

**Issue by AtharvaRathi** [0x5eba/Video-Meeting#23]
Hey there,
I am using your video meet but i want to set a maximum limit of number of participants in a room. So can you please say what to do so that i can have an option to set a maximum limit for the number of participants in a room.

Thanks,
Atharva.

**Comment by 0x5eba** [comment]
In the server, inside `join-call` check if `connections[path]` > K, if so return

**Comment by AtharvaRathi** [comment]
Hey there
Thank you for your reply. But I have seen it and it's in the app.js file. And what I am doing as I was just wanting one room for myself so instead of using any Vm to VPS I have just copied the code from your website. And it I working if we copy the code and directly use it on any simple web host like the web host which has the option to put only HTML CSS and js and PHP files, so I have used that.

So is there any way to do it from there?? i.e from just that public files with some js files??


Thanks,
Atharva.
