### ISSUE TITLE
unable to run in my localhost

### ISSUE THREAD

**Issue by shikhalakra22** [0x5eba/Video-Meeting#24]
can you please tell me the procedure on how to run the project on localhost.

**Comment by uttam8299** [comment]
1. First install Node on the machine.
2. If successfully installed, then navigate to your project folder and open command prompt.
3. Run 'npm start' and wait for a while. Let the npm do it's work.

**Comment by An-prog-hub** [comment]
@shikhalakra22  
After clone the project navigate folder path to the cmd and type ```npm install``` it will install the node_modules and after that 
run ```npm start``` 
![Capture](https://user-images.githubusercontent.com/67872399/98208863-09690400-1f64-11eb-9296-139477780d72.JPG)
