### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by 65d** [0x5eba/Video-Meeting#26]
HELP
Cannot GET /

**Comment by IbrahimBilalPrograms** [comment]
same problem idk what is causing it.

**Comment by Nisarga-Developer** [comment]
same problem

**Comment by wk989898** [comment]
try to set `"server": "set NODE_ENV=production && nodemon app.js "` in `package.json`,problem may be caused by `NODE_ENV`,
i solved by modify scripts

**Comment by ZamanMehdi** [comment]
@wk989898 still giving me the same error after modifying, can you help me with this?
Thanks

**Comment by 0x5eba** [comment]
Did you run `yarn install` and `yarn dev`?
You can use `npm install` and `npm run dev` if you prefer

**Comment by wk989898** [comment]
> @wk989898 still giving me the same error after modifying, can you help me with this?
> Thanks
"server": "set NODE_ENV=production&&nodemon app.js"
remove space (run on windows)

**Comment by ZamanMehdi** [comment]
still not working

**Comment by wk989898** [comment]
solved on windows:
if you run `dev` , modify `"dev": "concurrently -n 'server,client' -c 'red,green'  \"nodemon app.js\" \"set NODE_ENV=dev&& set PORT=8000&&react-scripts start\""`
if you run `server`,make sure you build it and modify `"server": "set NODE_ENV=production&&nodemon app.js"`

**Comment by Nisarga-Developer** [comment]
> solved on windows:
> if you run `dev` , modify `"dev": "concurrently -n 'server,client' -c 'red,green' \"nodemon app.js\" \"set NODE_ENV=dev&& set PORT=8000&&react-scripts start\""`
> if you run `server`,make sure you build it and modify `"server": "set NODE_ENV=production&&nodemon app.js"`

Same error again! 


```
_yarn run v1.22.5
$ concurrently -n 'server,client' -c 'red,green' "nodemon app.js" "set NODE_ENV=dev&& set PORT
=8000&&react-scripts start"
[server] [nodemon] 2.0.6
[server] [nodemon] to restart at any time, enter `rs`
[server] [nodemon] watching path(s): *.*
[server] [nodemon] watching extensions: js,mjs,json
[server] [nodemon] starting `node app.js`
[server] listening on 4001
[client] i ｢wds｣: Project is running at http://192.168.43.91/
[client] i ｢wds｣: webpack output is served from
[client] i ｢wds｣: Content not from webpack is served from C:\Users\rubyd\Desktop\Coding\Video-Meeting\public
[client] i ｢wds｣: 404s will fallback to /
[client] Starting the development server...
[client]
[client] Compiled with warnings.
[client]
[client] ./src/Video.js
[client]   Line 127:39:  Function declared in a loop contains unsafe references to variable(s) 'connections', 'socket', 'connections'  no-loop-func
[client]   Line 153:41:  Function declared in a loop contains unsafe references to variable(s) 'connections', 'socket', 'connections'  no-loop-func
[client]   Line 189:39:  Function declared in a loop contains unsafe references to variable(s) 'connections', 'socket', 'connections'  no-loop-func
[client]   Line 350:43:  Function declared in a loop contains unsafe references to variable(s) 'connections', 'socket', 'connections'  no-loop-func
[client]
[client] ./src/Home.js
[client]   Line 21:8:  'url' is already defined  no-redeclare
[client]
[client] Search for the keywords to learn more about each warning.
[client] To ignore, add // eslint-disable-next-line to the line before.
[client]_

```
Here are the outputs I got in the terminal & I am still getting the Cannot GET / error. 
@wk989898 @0x5eba

**Comment by wk989898** [comment]
> > solved on windows:
> > if you run `dev` , modify `"dev": "concurrently -n 'server,client' -c 'red,green' \"nodemon app.js\" \"set NODE_ENV=dev&& set PORT=8000&&react-scripts start\""`
> > if you run `server`,make sure you build it and modify `"server": "set NODE_ENV=production&&nodemon app.js"`
> 
> Same error again!
> 
> ```
> _yarn run v1.22.5
> $ concurrently -n 'server,client' -c 'red,green' "nodemon app.js" "set NODE_ENV=dev&& set PORT
> =8000&&react-scripts start"
> [server] [nodemon] 2.0.6
> [server] [nodemon] to restart at any time, enter `rs`
> [server] [nodemon] watching path(s): *.*
> [server] [nodemon] watching extensions: js,mjs,json
> [server] [nodemon] starting `node app.js`
> [server] listening on 4001
> [client] i ｢wds｣: Project is running at http://192.168.43.91/
> [client] i ｢wds｣: webpack output is served from
> [client] i ｢wds｣: Content not from webpack is served from C:\Users\rubyd\Desktop\Coding\Video-Meeting\public
> [client] i ｢wds｣: 404s will fallback to /
> [client] Starting the development server...
> [client]
> [client] Compiled with warnings.
> [client]
> [client] ./src/Video.js
> [client]   Line 127:39:  Function declared in a loop contains unsafe references to variable(s) 'connections', 'socket', 'connections'  no-loop-func
> [client]   Line 153:41:  Function declared in a loop contains unsafe references to variable(s) 'connections', 'socket', 'connections'  no-loop-func
> [client]   Line 189:39:  Function declared in a loop contains unsafe references to variable(s) 'connections', 'socket', 'connections'  no-loop-func
> [client]   Line 350:43:  Function declared in a loop contains unsafe references to variable(s) 'connections', 'socket', 'connections'  no-loop-func
> [client]
> [client] ./src/Home.js
> [client]   Line 21:8:  'url' is already defined  no-redeclare
> [client]
> [client] Search for the keywords to learn more about each warning.
> [client] To ignore, add // eslint-disable-next-line to the line before.
> [client]_
> ```
> 
> Here are the outputs I got in the terminal & I am still getting the Cannot GET / error.
> @wk989898 @0x5eba

it will automatic open browser. if not.please open http://localhost:8000/

**Comment by Shanmukhsvstp** [comment]
Hello sir, I have faced the same issue. But you can see that error shows that "NODE_ENV" is not recognized.
So, you can install it in that project by following command - "`npm install -g win-node-env`". Then try "`yarn run dev`".
That worked for me and also should fix your issue
