### ISSUE TITLE
microphone not working while sharing a screen

### ISSUE THREAD

**Issue by pdeivaraj** [0x5eba/Video-Meeting#32]
presenting screen the microphone not working

**Comment by 0x5eba** [comment]
Connect with 2 tabs

**Comment by pdeivaraj** [comment]
**@0x5eba thanks but we solved the issue**

`getDislayMedia = () => {
		if (this.state.screen) {
			if (navigator.mediaDevices.getDisplayMedia) {
				navigator.mediaDevices.getDisplayMedia({ video: true, audio: true })
					.then((stream) => {
						navigator.mediaDevices.getUserMedia({audio: true}).then((audio)=>{
							this.getDislayMediaSuccess(new MediaStream([audio.getTracks()[0], stream.getTracks()[0] ]))
						})
					})
					.catch((e) => console.log(e))
			}
		}
	}`
