### ISSUE TITLE
Are the videos encrypted end to end / secure? 

### ISSUE THREAD

**Issue by amrahsmaytas** [0x5eba/Video-Meeting#38]
Greetings and thanks for making this app open source, 
Can you give me some clarity on whether the video chat is end to end encrypted and secure? 

If no, how this can be achieved in your app? 

Thanks, 
Satyam.

**Comment by 0x5eba** [comment]
Yes is end-to-end encrypted, thanks to webrtc [webrtc-security.github.io](https://webrtc-security.github.io/)

**Comment by amrahsmaytas** [comment]
Thanks for the clarity!
