### ISSUE TITLE
i am unable to achieve sidebar layout like google-meet does

### ISSUE THREAD

**Issue by SharmaShagun2197** [0x5eba/Video-Meeting#5]
![Capture](https://user-images.githubusercontent.com/60870524/84705562-3860e800-af79-11ea-94f7-f9b9bd6f1134.PNG)

When "A" user clicks on "B" video image, it gets zoom on main screen and replaces the "A" main image

**Comment by 0x5eba** [comment]
I prefer my layout, if you don't like it you can change the code to do it as you want
